#!/usr/bin/env python3
import fileinput
import argparse

# Instantiate the parser
parser = argparse.ArgumentParser(description='Optional app description')

# Optional argument
parser.add_argument('--fn', type=str,
                    help='file name to convert Frame to VMAF_Frame')

args = parser.parse_args()


if __name__ == '__main__':
   ##Inputs
   filename=args.fn;
   with fileinput.FileInput(filename, inplace=True, backup='.bak') as file:
       for line in file:
          print(line.replace('Frame ', 'VMAF_Frame '), end='')
